### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by osenmukdav** [p-o-n-y/pony#10]
@a-kozlov-msu 
Комментарии на уже не русском языке 
https://github.com/p-o-n-y/pony/blob/44b89b351b2d3cb6a7d1250dbb115efd1f915730/pony.h#L21
и серый код
https://github.com/p-o-n-y/pony/blob/44b89b351b2d3cb6a7d1250dbb115efd1f915730/pony.c#L260
убираю?

**Comment by a-kozlov-msu** [comment]
Согласен, да

**Comment by osenmukdav** [comment]
@a-kozlov-msu 
https://github.com/p-o-n-y/pony/blob/44b89b351b2d3cb6a7d1250dbb115efd1f915730/pony.c#L381
Убираю?

**Comment by a-kozlov-msu** [comment]
Вместо TBD надо описать возвращаемое значение, почему убираем?

On Thursday, June 13, 2019, osenmukdav <notifications@github.com> wrote:
> @a-kozlov-msu
>
https://github.com/p-o-n-y/pony/blob/44b89b351b2d3cb6a7d1250dbb115efd1f915730/pony.c#L381
> Убираю?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/CcapwUbM-wWVS9TEIZoddjXXZrEYlXXR7HKiHL7awa1gGITc16dGAGTZtZp4DxlC-T-E9QYuyZu3_SEHGYUMBF_E_M6SCQsP6FYQjLw-8FZyLN2dhsmX0p27XMHLeg757lywqzmUd6iUCFWu2OFgihNwym2sgbHZG5Ga0Vv1pQsfkK12HYh_Vm2-OgBSSzdesDufZArNrru9O9TeFpJteiF2lHtXq3Gso7Qf3IP2Bg=s0-d-e1-ft#https://github.com/notifications/beacon/ALIKRCD5HY5V2SVB5MXDYDLP2H3INA5CNFSM4HWSQO22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXS2OSQ.gif>
