### ISSUE TITLE
Configuration outside groups

### ISSUE THREAD

**Issue by osenmukdav** [p-o-n-y/pony#13]
@a-kozlov-msu 
https://github.com/p-o-n-y/pony/blob/3d74440970b47e206f09281f1b7fde7c647caae6/pony.h#L175
Точно стоит выносить внешнюю часть конфигурации в core? Если я правильно понял, там ведь лежат неиспользуемые юзером переменные. Или по стандарту хостом внешняя часть конфигурации не используется?

**Comment by a-kozlov-msu** [comment]
В соответствии с этим:

github.com/p-o-n-y/pony/issues/18

можно вынести в settings

если не видишь противопоказаний, давай так и сделаем

**Comment by a-kozlov-msu** [comment]
Вынес в settings_cfg, предлагаю считать это стандартом.
