### ISSUE TITLE
Обнуление ссылок на подстроки конфигурации

### ISSUE THREAD

**Issue by osenmukdav** [p-o-n-y/pony#14]
Раз уж после освобождения ссылок на части пони (imu и т.д.) им присваивается NULL, стоит ли так же обнулять ссылки на подстроки конфигурации и их длины в функциях free?

**Comment by a-kozlov-msu** [comment]
Думал об этом, вроде бы это не имеет смысла. Части пони и их конфигурация
существуют или не существуют только вместе и никак иначе.

On Saturday, August 3, 2019, osenmukdav <notifications@github.com> wrote:
> Раз уж после освобождения ссылок на части пони (imu и т.д.) им
присваивается NULL, стоит ли так же обнулять ссылки на подстроки
конфигурации и их длины в функциях free?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/PczDel1OQ_PQI-8mnjwYD36-WdiOv2SuVlXxiC9_oKGGN0seNofMjHCvc4GAGObGrUx_DOzkqW4HZPI_pnj8OwBQR6c6DjnarLEVhF_s5z2R-vEMFnRrJsOyL0NMtgmZIxP857dzHXpZRiCFe1138dedXJPDXw-zIYgPHxMpjAAGa_UxtL_RR1yyVn0JvdALFbNfgywuzG576M8aST1Nw8NIB1Q=s0-d-e1-ft#https://github.com/notifications/beacon/ALIKRCAG42S2S5WTCT62HSTQCWWSRA5CNFSM4IJDMMDKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HDGJ7VA.gif>

**Comment by a-kozlov-msu** [comment]
Обнуление делается для указателей на выделяемую память, чтобы проверкой указателя на NULL можно было понять, допустимо ли обращение к нему. Так что в случае с подстроками конфигурации это не нужно.
