### ISSUE TITLE
define'ы в pony.h

### ISSUE THREAD

**Issue by osenmukdav** [p-o-n-y/pony#16]
@a-kozlov-msu 
https://github.com/p-o-n-y/pony/blob/1d0f76874daeeb3b626a71edcc493ca18b5595f3/pony.h#L7
Define'ы ведь обычно выносят в код хоста перед подключением библиотеки? PONY_LINAL оставим в pony.h? Или это просто временная мера?

**Comment by a-kozlov-msu** [comment]
Я думаю, этот дефайн вообще не нужен, надо изучить вопрос, вроде бы если
функции в программе не вызываются, то они и не линкуются, и объёма
программе не добавляют. Но это неточно, поэтому пока оставил его.

On Tuesday, August 6, 2019, osenmukdav <notifications@github.com> wrote:
> @a-kozlov-msu
>
https://github.com/p-o-n-y/pony/blob/1d0f76874daeeb3b626a71edcc493ca18b5595f3/pony.h#L7
> Define'ы ведь обычно выносят в код хоста перед подключением библиотеки?
PONY_LINAL оставим в pony.h? Или это просто временная мера?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/CQbGnLm_sGyEbQ2Nk2i_E9rnLTQFzI1qYIIGJOt4UGxMMXYx6LwK58NHBG57Wnvpxjt9Rj49lSJzTpS5o1xohpua9P_AFDbJCDtBrcZmCkDBr6oE8LhtNVZ7AJ1YMVK8GcI2L_DF49JN6Jm3iv8-g0xJlWQ64vV90gSg1B5IYz4yswS39iF7Zz_dkgKVwaktB1qlyhmMM34gGqgZCDXWLhgOBuU=s0-d-e1-ft#https://github.com/notifications/beacon/ALIKRCFPEU7G3E2VCKUUUZDQDCKXVA5CNFSM4IJO7PT2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HDPNNUA.gif>

**Comment by a-kozlov-msu** [comment]
Убрал
