### ISSUE TITLE
pony_strncmpeff, pony_locatesubstrn, pony_locatesubstreff

### ISSUE THREAD

**Issue by osenmukdav** [p-o-n-y/pony#17]
pony_strncmpeff, pony_locatesubstrn и pony_locatesubstreff сейчас никак не используются. Всё равно пока оставляем их?

**Comment by a-kozlov-msu** [comment]
Мне казалось, я убрал все те, которые не используются. Так что я в смятении)

On Tuesday, August 6, 2019, osenmukdav <notifications@github.com> wrote:
> pony_strncmpeff, pony_locatesubstrn и pony_locatesubstreff сейчас никак
не используются. Всё равно пока оставляем их?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/6dDl1fh7LYPxSN68J3rZ6wKR5j7bLA5BhQpuZbdkJR8HIZk8Oh039haXy8nWGMR4LkY3twyKe5KUjYxVYSwsq5IduOluygaPw0PCuRkP8wOR7EdFjtrYD6rg9st20_lOTu1KPnM6E7SLA_w1nMHVHyvz6b7SMrMhC_FcpWNYw1ziwk9ka2eBkqEmd2mqCAO7wS93TZ-3bOJsBmhRRFD-aPTW0TI=s0-d-e1-ft#https://github.com/notifications/beacon/ALIKRCGOPUYCIZKKOBQYGTDQDCLG7A5CNFSM4IJPAKJ2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HDPOEWA.gif>

**Comment by a-kozlov-msu** [comment]
Ты прав
