### ISSUE TITLE
Уточнение комментариев (1)

### ISSUE THREAD

**Issue by osenmukdav** [p-o-n-y/pony#18]
https://github.com/p-o-n-y/pony/blob/1d0f76874daeeb3b626a71edcc493ca18b5595f3/pony.h#L148-L152

Наверное описания длин стоит поменять местами, иначе непонятно.

Кстати, общие подчасти строк конфигурации мы теперь называем settings, или это только в этом случае?

**Comment by a-kozlov-msu** [comment]
Описания надо просто поменять немного, это в процессе родилось.

Насчёт settings хорошая идея сделать так везде.

On Tuesday, August 6, 2019, osenmukdav <notifications@github.com> wrote:
>
https://github.com/p-o-n-y/pony/blob/1d0f76874daeeb3b626a71edcc493ca18b5595f3/pony.h#L148-L152
>
> Наверное описания длин стоит поменять местами, иначе непонятно.
>
> Кстати, общие подчасти строк конфигурации мы теперь называем settings,
или это только в этом случае?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/DIpeXs9LlrbvXDk3D1_Egk0YPDFBuVQEWOAJlB9Qyv8GuKQUanoAWKNPfHSmm0iAjMXDLP8Eq0LqwGf7X_l2Q1YnYJM7TU9UTY2bNvWbZKuhYta4Ku9sepKK8i2UpOEmPXJWw-SPaxenv3VYLjzXL4vAlHn9XcTF8Z_K-mn5lFq_w2M_PBCu-WMFwcyIMz7aZ7RG14YVBOV8tT-iifmigTe1J7w=s0-d-e1-ft#https://github.com/notifications/beacon/ALIKRCDTI7GURMK2YFIKRATQDCM3PA5CNFSM4IJPDHW2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HDPQSHA.gif>

**Comment by a-kozlov-msu** [comment]
Done
