### ISSUE TITLE
Константы gps

### ISSUE THREAD

**Issue by osenmukdav** [p-o-n-y/pony#19]
1. Константы для gps одинаковые, но у каждого gnss свои, то есть под одно и то же при нескольких gnss&apos;ах память на одинаковые вещи выделяться несколько раз. Можно решить, скажем, переносом структуры из gnss&apos;а в pony_bus.<br>

2. Присваивание значений происходит даже при отсутствии gps. Возможно тогда стоит перенести структуру с константами в gps? Или наоборот, сделать её общей (переназвать в gnss_const)?<br>

3. При n gnss&apos;ов значения констант присваиваютя n*(n+1)/2 раз. Это можно решить переносом строки из pony_init_gnss<br>
https://github.com/p-o-n-y/pony/blob/1d0f76874daeeb3b626a71edcc493ca18b5595f3/pony.c#L465<br>
на строку 677 в pony_init.
Или использованием одной общей структуры.

**Comment by a-kozlov-msu** [comment]
1,2. Ты прав, но я не придумал, как обойти недостатки. Пока смирился с
избыточностью, т.к. констант мало. Константы у GPS свои, и некоторые
аналогичные им в ГЛОНАСС имеют немного другие значения, и это важно,
поэтому делать gnss_const с ходу нетривиально. На шину переносить не очень
хорошо при отсутствии gnss. Придумаем, на чём остановиться, но позже. Будут
(ещё) идеи, или детализация этих, или аргументы - как лучше - хорошо.

3. Не понял с ходу, надо будет подумать.

On Tuesday, August 6, 2019, osenmukdav <notifications@github.com> wrote:
> Константы для gps одинаковые, но у каждого gnss свои, то есть под одно и
то же при нескольких gnss'ах память на одинаковые вещи выделяться несколько
раз. Можно решить, скажем, переносом структуры из gnss'а в pony_bus.
>
> Присваивание значений происходит даже при отсутствии gps. Возможно тогда
стоит перенести структуру с константами в gps? Или наоборот, сделать её
общей (переназвать в gnss_const)?
>
> При n gnss'ов значения констант присваиваютя n*(n+1)/2 раз. Это можно
решить переносом строки из pony_init_gnss
>
>
https://github.com/p-o-n-y/pony/blob/1d0f76874daeeb3b626a71edcc493ca18b5595f3/pony.c#L465
>
> на строку 677 в pony_init.
> Или использованием одной общей структуры.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/r8IDdp_Ck3sJlCfTEt79gaf6SW69UyGWz4ia9Ihhzw1TotiMyqCGIsjwYmdCrVC1yTBcc4-sTqSANFAhQtYfZixzFjh-o3uzYi7VS56Pgch0yD7Qh7J04bjB5yOQo9C_zgFIp7LBjyy9oOt9cqCv9a6UuowcjR-jXs_h3zRBCRB7GVTKEgyPx87ebLHIQD3cwtt2F3WzDOw9hfv0P_tIlvEGnd8=s0-d-e1-ft#https://github.com/notifications/beacon/ALIKRCDVSPQGEK56DSO4KLLQDGYENA5CNFSM4IJYTQIKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HDWEQNA.gif>
