### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by osenmukdav** [p-o-n-y/pony#2]
pony.c line 210
Нужно добавить && (*groupptr)[*grouplen] != '}' к условиям, так как поиск "def" используя "gnss:" в "{gnss: {gps: abc} def} ghi" вернёт длину, соответствующую "def} ghi"

```
		// determine the length, counting until the end of the string or when a group started
for (; (*groupptr)[*grouplen] && (*groupptr)[*grouplen] != '{'; (*grouplen)++);
```

**Comment by a-kozlov-msu** [comment]
Это же поиск параметров вне группы? Они либо в начале конфигурации, либо в конце. Либо мне надо ещё подумать. И ещё не понял про 'поиск "def" используя "gnss:" '

**Comment by a-kozlov-msu** [comment]
Верно

**Comment by a-kozlov-msu** [comment]
fixed
commit 69668d4239e3a788f8332d913474680b315fb755 (HEAD -> master, origin/master, origin/HEAD)
Author: a-kozlov-msu <a.kozlov.msu@gmail.com>
Date:   Fri Apr 19 16:36:41 2019 +0300
