### ISSUE TITLE
Микрооптимизация (1)

### ISSUE THREAD

**Issue by osenmukdav** [p-o-n-y/pony#20]
В
https://github.com/p-o-n-y/pony/blob/1d0f76874daeeb3b626a71edcc493ca18b5595f3/pony.c#L364-L375
и
https://github.com/p-o-n-y/pony/blob/1d0f76874daeeb3b626a71edcc493ca18b5595f3/pony.c#L433-L444
финальное приравнивание NULL'у нужно внести в конец блока if, так как в случае, если gps->sat или glo->sat равны NULL, им всё равно присваивается NULL.

**Comment by a-kozlov-msu** [comment]
Если видишь, что точно так, делай.

On Tuesday, August 6, 2019, osenmukdav <notifications@github.com> wrote:
> В
>
https://github.com/p-o-n-y/pony/blob/1d0f76874daeeb3b626a71edcc493ca18b5595f3/pony.c#L364-L375
> и
>
https://github.com/p-o-n-y/pony/blob/1d0f76874daeeb3b626a71edcc493ca18b5595f3/pony.c#L433-L444
> финальное приравнивание NULL'у нужно внести в конец блока if, так как в
случае, если gps->sat или glo->sat равны NULL, им всё равно присваивается
NULL.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/wUveaApiEzmt505FSCCSQcKeFSI-iGde48kAM-I_dbRDt43Jq8OpiDmELgVWsgn_SgYDkiGX4qYl0lLyTjdnePNDb9cIgXR-owtEMZb1-a6ur1tRC4_i2aHwh9D96Nhd1ksMZcSSXInHcHdcApa4CZXrOLdZjECwSRQWnSranboVfvWaqTtiaOG5YvLqeUrigCQAN5BlCqic5kge0ArelfT58cI=s0-d-e1-ft#https://github.com/notifications/beacon/ALIKRCCXUBUCYRXOGMPBL63QDG2GHA5CNFSM4IJYXYR2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HDWIBMQ.gif>
