### ISSUE TITLE
pony_terminate working incorrectly

### ISSUE THREAD

**Issue by osenmukdav** [p-o-n-y/pony#21]
Right now pony_terminate makes plugins run in finish mode twice

**Comment by a-kozlov-msu** [comment]
I will look into this on weekend.

On Friday, November 15, 2019, osenmukdav <notifications@github.com> wrote:
> Right now pony_terminate makes plugins run in finish mode twice
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/LF_4KjpWVv8_awLRdVl894VNmVPJbyyx8ZnA8QWgH12GEmah89-OZFFX6OmzdgEKXjG5ULmGzsOIHU0EfCgpxXmCVGv-RUgWeBvfI1Kxhl3cBSKT6ykinSXTqNmgZVxGpufKJedcYNS2oTBMzFyNzRaIcnvz9xdxMcgbzSzUPRA8ss41iw81qrsmPhz7iblhjnbDgr4-amGnQ7KCbX-48jNnVyc=s0-d-e1-ft#https://github.com/notifications/beacon/ALIKRCA24L2A3E6AXQNTPQTQTWBJDA5CNFSM4JNO26SKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HZMIBOQ.gif>

**Comment by osenmukdav** [comment]
I have already most likely fixed this, will test and commit soon. Made an issue just as a reminder.
By the way, this will require an extra char variable.

> 
> I will look into this on weekend.
> On Friday, November 15, 2019, osenmukdav ***@***.***> wrote: Right now pony_terminate makes plugins run in finish mode twice — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.<
> https://ci6.googleusercontent.com/proxy/LF_4KjpWVv8_awLRdVl894VNmVPJbyyx8ZnA8QWgH12GEmah89-OZFFX6OmzdgEKXjG5ULmGzsOIHU0EfCgpxXmCVGv-RUgWeBvfI1Kxhl3cBSKT6ykinSXTqNmgZVxGpufKJedcYNS2oTBMzFyNzRaIcnvz9xdxMcgbzSzUPRA8ss41iw81qrsmPhz7iblhjnbDgr4-amGnQ7KCbX-48jNnVyc=s0-d-e1-ft#https://github.com/notifications/beacon/ALIKRCA24L2A3E6AXQNTPQTQTWBJDA5CNFSM4JNO26SKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HZMIBOQ.gif>
