### ISSUE TITLE
Whad does "single-receiver gnss support to the bus" mean?

### ISSUE THREAD

**Issue by osenmukdav** [p-o-n-y/pony#22]
В данный момент в вики пишу [историю изменений](https://github.com/p-o-n-y/pony/wiki/Changelog), в основном направленную на разработчиков плагинов, поэтому стараюсь в ней описывать новые возможности для них без того, чтобы им пришлось самим разбираться в коммитах. Так что эти вопросы будут поступать ещё некоторое время. Когда история изменений будет в приличном состоянии, добавлю ссылку на неё в readme. 

Данный вопрос про [летний major update](https://github.com/p-o-n-y/pony/commit/7fe8de3995ac83ea5c2d560b8177ef90ae839a5d), а именно что значит пункт added single-receiver gnss support to the bus.

**Comment by a-kozlov-msu** [comment]
Это была поддержка одного приёмника gnss. Уже тогда были планы на поддержку многоантенных систем, поэтому и указал single-receiver.

**Comment by a-kozlov-msu** [comment]
> 
> 
> В данный момент в вики пишу [историю изменений](https://github.com/p-o-n-y/pony/wiki/Changelog), в основном направленную на разработчиков плагинов, поэтому стараюсь в ней описывать новые возможности для них без того, чтобы им пришлось самим разбираться в коммитах. Так что эти вопросы будут поступать ещё некоторое время. Когда история изменений будет в приличном состоянии, добавлю ссылку на неё в readme.
> 
> Данный вопрос про [летний major update](https://github.com/p-o-n-y/pony/commit/7fe8de3995ac83ea5c2d560b8177ef90ae839a5d), а именно что значит пункт added single-receiver gnss support to the bus.

Вопрос закрыт?

**Comment by osenmukdav** [comment]
Да

вт, 3 мар. 2020 г., 23:44 a-kozlov-msu <notifications@github.com>:
