### ISSUE TITLE
Are galileo and beidou supported?

### ISSUE THREAD

**Issue by osenmukdav** [p-o-n-y/pony#27]
Если они поддерживаются, было ли это начиная с https://github.com/p-o-n-y/pony/commit/e81e75820b4e4b2fee6c8f865a93d81ddf9e8fa7 для gal и с https://github.com/p-o-n-y/pony/commit/5baff318a06f70ab9265b4ff1ffcc9fc5e517ddb для bds?

**Comment by a-kozlov-msu** [comment]
Проверил, всё верно

> 
> 
> Если они поддерживаются, было ли это начиная с [e81e758](https://github.com/p-o-n-y/pony/commit/e81e75820b4e4b2fee6c8f865a93d81ddf9e8fa7) для gal и с [5baff31](https://github.com/p-o-n-y/pony/commit/5baff318a06f70ab9265b4ff1ffcc9fc5e517ddb) для bds?
