### ISSUE TITLE
pony_gnss_gps_sat  is exactly the same as  pony_gnss_glo_sat

### ISSUE THREAD

**Issue by osenmukdav** [p-o-n-y/pony#4]
Поскольку количество эфемерид не хардкодится, между структурами pony_gnss_gps_sat и pony_gnss_glo_sat нет разницы.
Всё равно делаем одинаковые структуры, или переименовываем pony_gnss_gps_sat в pony_gnss_sat и используем для всех?

**Comment by a-kozlov-msu** [comment]
Правильный вопрос. Отличия могут появиться, когда будет реализовано первое реальное приложение с поддержкой ГЛОНАСС, но с ходу придумать не могу. Поэтому пока без необходимости лишние сущности оставлять не будем, переименовывай и используй для всех. 

Хоть изначально и казалось, что отличия будут.

**Comment by osenmukdav** [comment]
@a-kozlov-msu 
На pony_gnss_sat переименовал.
pony_gnss_gps и pony_gnss_glo тоже одинаковые. Оставляем или меняем?

**Comment by a-kozlov-msu** [comment]
Эти точно будут разные, не сильно, но будут. Так что просто дублируй для будущей проработки.
