### ISSUE TITLE
freeing memory of *obs in pony_gnss_gps_sat

### ISSUE THREAD

**Issue by osenmukdav** [p-o-n-y/pony#5]
Так как определяется во время выполнения, ответственность за освобождение памяти несёт пользователь?

**Comment by a-kozlov-msu** [comment]
За память, выделенную PONY, отвечает PONY, за память, выделенную хостом - отвечает хост. Или я забыл контекст.

**Comment by a-kozlov-msu** [comment]
Вспомнил контекст. Да, по-нашему этот человек называется "пользователь", он несёт. Хотя некоторые рекомендации я предвижу по этой переменной в документации на pony. Но выделения и освобождения это не касается.
