### ISSUE TITLE
"conf" to "cfg"

### ISSUE THREAD

**Issue by osenmukdav** [p-o-n-y/pony#6]
На сейчас переименовано только в частях шины, нужно ли переименовывать в методах тоже, для большей читаемости?

**Comment by a-kozlov-msu** [comment]
Да, это логично

**Comment by osenmukdav** [comment]
Единственное, что осталось "configuration" - название параметра у init
https://github.com/p-o-n-y/pony/blob/28e4e2adaa20c06555f4d6829a4866132f54c1da/pony.c#L367
Тоже меняю?

**Comment by osenmukdav** [comment]
> 
> 
> Единственное, что осталось "configuration" - название параметра у init
> 
> https://github.com/p-o-n-y/pony/blob/28e4e2adaa20c06555f4d6829a4866132f54c1da/pony.c#L367
> 
> Тоже меняю?

@a-kozlov-msu

**Comment by a-kozlov-msu** [comment]
> 
> 
> > Единственное, что осталось "configuration" - название параметра у init
> > https://github.com/p-o-n-y/pony/blob/28e4e2adaa20c06555f4d6829a4866132f54c1da/pony.c#L367
> > 
> > Тоже меняю?
> 
> @a-kozlov-msu

Меняй, это логично
