### ISSUE TITLE
add dynamic memory allocation checks

### ISSUE THREAD

**Issue by a-kozlov-msu** [p-o-n-y/pony#8]
После каждого динамического выделения памяти должна быть проверка на нулевой указатель (NULL).

Функции ядра pony, в которых происходит выделение памяти, должны возвращать значение char 0 или 1, которое должно проверяться вызывающей функцией.

Это касается pony_init, pony_setDASize и возможно других.

**Comment by osenmukdav** [comment]
Вроде как сделал:
https://github.com/p-o-n-y/pony/commit/a4dd096d25e14a84b2f9c34c6861786767e4f677
Нужно проверить, всё ли я обработал в pony.c. Ещё я немного переделаю часть с маджвиком.

**Comment by osenmukdav** [comment]
> 
> 
> Вроде как сделал:
> [a4dd096](https://github.com/p-o-n-y/pony/commit/a4dd096d25e14a84b2f9c34c6861786767e4f677)
> Нужно проверить, всё ли я обработал в pony.c. Ещё я немного переделаю часть с маджвиком.

@a-kozlov-msu 

Пока что делаю маджвика, но нужно посмотреть, сделал ли я проверки в pony.c так, как надо.

**Comment by a-kozlov-msu** [comment]
> 
> 
> Вроде как сделал:
> [a4dd096](https://github.com/p-o-n-y/pony/commit/a4dd096d25e14a84b2f9c34c6861786767e4f677)
> Нужно проверить, всё ли я обработал в pony.c. Ещё я немного переделаю часть с маджвиком.

Проверю глазами потом. Я пытался найти способ ограничить heap size для приложения под Windows, не нашёл. Наткнулся на соответствующие настройки линкера в MS VS, но они не дали эффекта, по умолчанию под приложение резервируется 1Мб, этого более чем достаточно для инициализации шины.

Может быть ты сможешь найти. Это самый прямой и надёжный способ проверить верно ли в принципе обрабатываются ошибки выделения памяти, а дальше все проверки делать аналогично той, на которой будет срабатывать принудительное ограничение памяти, если мы его найдём.

**Comment by a-kozlov-msu** [comment]
> 
> 
> Вроде как сделал:
> [a4dd096](https://github.com/p-o-n-y/pony/commit/a4dd096d25e14a84b2f9c34c6861786767e4f677)
> Нужно проверить, всё ли я обработал в pony.c. Ещё я немного переделаю часть с маджвиком.

Переделывать это полезно, в принципе. Каким бы это ни казалось малополезным занятием, с каждым новым рефокторингом/версией ты растёшь.

Хотя может быть обидно время тратить на то, что уже работает.

**Comment by osenmukdav** [comment]
Исправил баг: 44b89b351b2d3cb6a7d1250dbb115efd1f915730

Тогда делаю маджвика и закрываю issue.

**Comment by a-kozlov-msu** [comment]
> Исправил баг: [44b89b3](https://github.com/p-o-n-y/pony/commit/44b89b351b2d3cb6a7d1250dbb115efd1f915730)
> 
> Тогда делаю маджвика и закрываю issue.

Off course
