### ISSUE TITLE
move pony internal service functions declaration to pony.c

### ISSUE THREAD

**Issue by a-kozlov-msu** [p-o-n-y/pony#9]
Все определения функций pony, за исключением тспользуемых хостом  add_plugin, init, step и terminate нужно перенести в pony.c, так как использовать их предполагается только там.

Возможно, что какие-то мы перенесём обратно  для использования юзером или добавим в будущем (например предполагается библиотека функций для работы с матрицами), но сейчас это внутренние функции pony, которые не должны появляться в коде хоста при включении pony.h.

**Comment by osenmukdav** [comment]
В pony.h кроме add_plugin, init, step и terminate, если я не ошибаюсь, есть только функции с
https://github.com/p-o-n-y/pony/blob/607e9fdf25b58e58905dbc28dfdf4b638bb83328/pony.h#L8
по
https://github.com/p-o-n-y/pony/blob/607e9fdf25b58e58905dbc28dfdf4b638bb83328/pony.h#L17
Эти функции не используются в pony.c, они все для юзеров. К тому же без них сейчас маджвик на основе пони не будет работать, они там напрямую используются.
Можно сделать дополнительные файлы, но это так себе.
Можно использовать #ifdef _USE_STD_PONY_EXTRACT_FUNCS (предлагаю слово для включения ещё обсудить). Тогда они не будут появляться в коде хоста сразу, а только при #define ...
Примерно как с #define _USE_MATH_DEFINES, юзер может писать сам, а может использовать готовые куски кода.

Как именно делаем?

**Comment by a-kozlov-msu** [comment]
Раз Маджвик не будет работать, то оставляй. Но функции достаточно стандартные , чтобы дублирование их я бы назвал избыточным. Это увеличивает описание, но не совсем по теме назначения именно pony. Поскольку мы в любом случае описываем общий синтаксис конфигурации с разделами и скобками, но реализацию и синтаксис внутри разделов оставляем юзеру. Соответственно, навязывать конкретные функции или даже лишний #define - не очень хорошее решение (как и в math.h, которого, кстати, раньше не было, я бы сказал очень нелогично его ввели вообще). Как бы навязывать юзеру наш особый парсинг строк. Хватит и так инфы.

Так что, чтобы не тратить время сейчас на не самое важное:
1. Код оставляй как есть.
2. В описания для юзера эти функции не вносите.
3. Тикет снимаем.
